In [17]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

# 03. 넘파이

## - 넘파이 ndarray 개요

In [5]:
import numpy as np

In [11]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


- array1 : 1차원  
- array2 : 2차원, 2개의 로우와 3개의 칼럼  
- array3 : 2차원, 1개의 로우와 3개의 칼럼 

In [24]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'. format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


## - ndarray의 데이터 타입

- ndarray내의 데이터 타입은 같은 데이터 타입만 가능  

In [30]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [32]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


- int와 문자열이 섞여있으면: 문자열로 변환
- int와 float 섞여있으면: float로 변환
- astype() : 데이터값 타입 변경

In [36]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


## - ndarray를 편리하게 생성하기 - arange, zeros, ones

- arange() : 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

In [44]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


- zeros() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray 반환
- ones() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1으로 채운 해당 shape를 가진 ndarray 반환
- 함수 인자로 dtype 정해주지 않으면 디폴트로 float64형의 데이터

In [50]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## - ndarray의 차원과 크기를 변경하는 reshape()

In [55]:
array1 = np.arange(10)
print('array1: \n' , array1)

array2 = array1.reshape(2,5)
print('array2: \n' , array2)

array3 = array1.reshape(5,2)
print('array3: \n' , array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [65]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


- array2 = array1.reshape(-1,5) : 로우 인자가 -1, 칼럼 인자가 5  
  array1과 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개 칼럼에 맞는 로우를 자동으로 생성해 변환하라는 의미  
  10개의 1차원 데이터와 호환될 수 있는 고정된 5개 칼럼에 맞는 로우 개수는 2이므로 2x5의 2차원 ndarray로 변환
- array3 = array1.reshape(5,-1)  
  10개의 1차원 데이터와 호환될 수 있는 고정된 5개 로우에 맞는 칼럼 개수는 2이므로 5x2의 2차원 ndarray로 변환 
- 호환될 수 없는 형태는 변환될 수 없음

- reshape(-1,1) 같은 형태로 자주 사용  
  원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환  

In [76]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d: \n' , array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5: \n' , array5.tolist())
print('array5 shape:' , array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6: \n' , array6.tolist())
print('array6 shape:' , array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

1. 특정한 데이터만 추출
2. 슬라이싱(slicing)
3. Fancy indexing
4. Boolean indexing


### 단일 값 추출

In [88]:
array1 = np.arange(start=1, stop=10)
print('array1:' , array1)

value = array1[2]
print('value:' , value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


- 인덱스는 0부터 시작함 주의!
- 마이너스 기호 사용하면 맨 뒤에서부터 데이터 추출

In [103]:
print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8


In [111]:
# 데이터값 수정하기

array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [115]:
# 다차원 ndarray에서 단일 값 추출

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


- axis 0 : 로우 방향의 축, axis 1 : 칼럼 방향의 축
- [row=0, col=1] 인덱싱은 [axis 0=0, axis 1=1]이 정확한 표현
- 3차원 array는 axis 0, axis 1, axis 2로 3개의 축을 가짐

### 슬라이싱

In [123]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array1)
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


- ':' 기호 앞에 시작 인덱스 생략: 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스 생략: 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스 생략: 맨 처음/맨 마지막 인덱스로 간주

In [128]:
array1 = np.arange(start=1, stop=10)
print(array1)

array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [142]:
# 2차원 ndarray에서 슬라이싱으로 데이터에 접근하기

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [144]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱(Fancy indexing)

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [151]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱(Boolean indexing)

조건 필터링과 검색을 동시에!  
조건에 따라 True/False값 반환, True값에 해당하는 인덱스값만 저장하고 반환

In [154]:
array1 = np.arange(start=1, stop=10)

# [ ] 안에 array1d > 5 Boolean indexing 적용
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


## 행렬의 정렬 - sort()와 argsort()

### 행렬 정렬

- np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None
- 내림차순 정렬은 [::-1] 적용

In [162]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [185]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [8 5 3 1]


In [169]:
# 2차원 이상의 행렬 정렬
# axis0은 수직 방향, axis1은 수평 방향

array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬: \n', sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

- np.argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [183]:
org_array = np.array([3,1,8,5])

sort_indices = np.argsort(org_array)
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


- argsort()

In [191]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순 정렬 시 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순 정렬 시 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)

- np.dot()

In [194]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과: \n', dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


### 전치 행렬

- transpose()

In [200]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)

A의 전치 행렬: 
 [[1 3]
 [2 4]]


# 데이터 핸들링 - 판다스

## 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [206]:
import pandas as pd

In [212]:
titanic_df = pd.read_csv('titanic_train.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [214]:
print('titanic 변수 type:' , type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

- 별다른 파라미터 지정이 없으며 파일의 맨 처음 로우를 칼럼명으로 인지
- 맨 왼쪽은 Index

In [219]:
print('DataFrame 크기:' , titanic_df.shape)

DataFrame 크기: (891, 12)


- info( ) : 총 데이터 건수, 데이터 타입, null 건수
- describe( ) : 칼럼별 숫자형 데이터값의 n-percentile 분포도, 평균값, 최댓값, 최솟값
    - 오직 숫자형(int, float 등) 칼럼의 분포도만 조사하며 object 타입은 자동으로 출력에서 제외시킴
    - 해당 숫자 칼럼이 숫자형 카테고리 칼럼인지 판단할 수 있게 도와줌

In [221]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [223]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

- value_count( ) : 해당 칼럼값의 유형과 건수 확인, 많은 건수 순서대로 정렬되어 값을 반환

In [231]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


- DataFrame의 [ ] 연산자 내부에 칼럼명을 입력하면 해당 칼럼에 해당하는 Series 객체를 반환
- Series는 Index와 단 하나의 칼럼으로 구성된 데이터 세트

In [244]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [246]:
titanic_pclass.head()

# Series의 Index , Series의 데이터 값

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [252]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
Pclass
3    491
1    216
2    184
Name: count, dtype: int64


- 인덱스는 단순히 순차 값과 같은 의미 없는 식별자만 할당하는 것이 아니라 고유성이 보장된다면 의미 있는 데이터값 할당도 가능
- value_count()는 칼럼 값별 데이터 건수를 반환하므로 고유 칼럼 값을 식별자로 사용 가능
- 인덱스는 DataFrame, Series가 만들어진 후에도 변경 가능, 숫자형뿐만 아니라 문자형도 가능
- 단, 모든 인덱스는 고유성이 보장돼야 한다.

In [257]:
print('titanic_df 데이터 건수:', titanic_df.shape[0])
print('기본 설정인 dropna=True로 value_counts()')
# value_counts()는 디폴트로 dropna=True이므로 value_counts(dropna=True)와 동일
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False)) # null값 포함

titanic_df 데이터 건수: 891
기본 설정인 dropna=True로 value_counts()
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64


## DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

### 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

In [265]:
import numpy as np

col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

# 리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame: \n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame: \n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame: 
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame: 
    col1
0     1
1     2
2     3


- 1차원 형태의 데이터를 기반으로 DataFrame 생성하므로 칼럼명이 1개만 필요
- 2차원 형태의 데이터를 기반으로 DataFrame 생성: 2행3열 형태의 리스트와 ndarray를 기반으로 생성하므로 칼럼명은 3개 필요

In [272]:
# 3개의 칼럼명이 필요함
col_name2 = ['col1','col2','col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)

df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [274]:
# Key는 문자열 칼럼명으로 매핑, Value는 리스트 형(또는 ndarray) 칼럼 데이터로 매핑
dict = {'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


### DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

In [285]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), '\n df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> 
 df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [287]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


## DataFrame의 칼럼 데이터 세트 생성과 수정

In [291]:
titanic_df['Age_0'] = 0
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  
3      0            113803  53.1000  C123        S      0  
4      0            373450   8.0500   NaN        S      0

In [297]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   
3      0            113803  53.1000  C123        S      0      350.0   
4      0            373450   8.0500   NaN        S      0      350.0   

   Family_No  
0          2  
1          2  
2          1  
3          2  
4          1

In [299]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   
3      0            113803  53.1000  C123        S      0      450.0   
4      0            373450   8.0500   NaN        S      0      450.0   

   Family_No  
0          2  
1          2  
2          1  
3          2  
4          1

## DataFrame 데이터 삭제

- drop() 메서드
- DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
- axis 값에 따라 특정 칼럼 또는 로우를 드롭 (axis0은 로우 방향 축, 1은 칼럼 방향 축)
    - labels에 원하는 칼럼명을 입력하고 axis=1을 입력하면 지정된 칼럼 드롭
    - axis=0을 입력하면 특정 로우를 드롭
    - axis=1 많이 사용, axis=0은 이상치 데이터 삭제하는 경우 주로 사용

In [302]:
# Age_0 칼럼 삭제
titanic_drop_df = titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      320.0          2  
1      0          PC 17599  71.2833   C85        C      480.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0          1  
3      0            113803  53.1000  C123        S      450.0          2  
4      0            373450   8.0500   NaN        S      450.0          1

- inplace
    - 디폴트 값이 False - 자기 자신의 DataFrame의 데이터는 삭제하지 않고, 삭제된 결과 DataFrame 반환
    - inplace=True로 설정하면 자신의 DataFrame의 데이터 삭제
    - 여러 개의 칼럼 삭제하려면 리스트 형태로 입력
    - 주의점: inplace=True로 설정하면 반환값이 None이 되므로 다시 자신의 DataFrame 객체로 할당하면 안 됨

In [304]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값:', drop_result)
titanic_df.head()

inplace=True로 drop 후 반환된 값: None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [308]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('### before axis 0 drop ###')
print(titanic_df.head(3))

titanic_df.drop([0,1,2], axis=0, inplace=True)

print('### after axis 0 drop ###')
print(titanic_df.head(3))

### before axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
### after axis 0 drop ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


### <정리> drop() 메서드에서 axis와 inplace 인자를 적용해 DataFrame을 변경하는 방식
- axis: DataFrame의 로우를 삭제할 때는 axis=0, 칼럼을 삭제할 때는 axis=1
- 원본 DF은 유지하고 드롭된 DF을 새롭게 객체 변수로 받고 싶다면 inplace=False로 설정(디폴트 값이 False)
    - 예: titanic_drop_df = titanic_df.drop('Age_0', axis=1, inplace=False)
- 원본 DF에 드롭된 결과를 적용할 경우에는 inplace=True 적용
    - 예: titanic_df.drop('Age_0', axis=1, inplace=True)
- 원본 DF에서 드롭된 DF을 다시 원본 DF 객체 변수로 할당하면 원본 DF에서 드롭된 결과를 적용할 경우와 같음(단, 기존 원본 DF 객체 변수는 메모리에서 추후 제거됨)
    - 예: titanic_df = titanic_df.drop('Age=0', axis=1, inplace=False)


## Index 객체

In [319]:
# 원본 파일 다시 로딩
titanic_df = pd.read_csv('titanic_train.csv')

# index 객체 추출
indexes = titanic_df.index
print(indexes)

# index 객체를 실제 값 array로 변환
print('Index 객체 array값: \n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값: 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 23

In [321]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [323]:
# 한 번 만들어진 DF 및 Series의 Index 객체는 함부로 변경할 수 없음
indexes[0] = 5

TypeError: Index does not support mutable operations

In [327]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series +3: \n', (series_fair + 3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.9493
Fair Series +3: 
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


- reset_index() : 새롭게 인덱스를 연속 숫자 형으로 할당, 기존 인덱스는 'index'라는 새로운 칼럼명으로 추가
- 인덱스가 연속된 int 숫자형 데이터가 아닐 경우 사용
- 적용 시 DF가 반환됨(칼럼이 2개가 되므로)
- drop=True로 설정하면 기존 인덱스는 드롭됨, Series로 유지

In [329]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [335]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### after reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

# 왜 교재랑 좀 다르게 나오지???

### before reset_index ###
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### after reset_index ###
   Pclass  count
0       3    491
1       1    216
2       2    184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


## 데이터 셀렉션 및 필터링

### DataFrame의 [ ] 연산자

- DF 바로 뒤에 있는 [ ] 안에 들어갈 수 있는 것은 칼럼명 문자(또는 칼럼명의 리스트 객체), 또는 인덱스로 변환 가능한 표현식
- 칼럼만 지정할 수 있는 '칼럼 지정 연산자'로 이해하기

In [341]:
print('단일 칼럼 데이터 추출: \n', titanic_df[ 'Pclass' ].head(3))
print('\n여러 칼럼의 데이터 추출: \n', titanic_df[ ['Survived','Pclass'] ].head(3))
print('[]안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

단일 칼럼 데이터 추출: 
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출: 
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [346]:
# 인덱스 형태로 변환 가능한 표현식
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [354]:
# 불린 인덱싱
titanic_df[ titanic_df['Pclass']==3 ].head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

- DF 바로 뒤의 [] 연산자는 넘파이의 []나 Series의 []와는 다름
- DF 바로 뒤의 [] 내 입력값은 칼럼명(또는 칼럼의 리스트)를 지정해 지정 연산에 사용하거나 불린 인덱스 용도로만 사용해야
- DF[0:2]와 같은 슬라이싱 연산으로 데이터를 추출하는 방식은 사용하지 않는 게 좋음

### DataFrame iloc[ ] 연산자
- iloc[] : 위치 기반 인덱싱. 행과 열 위치를, 0을 출발점으로 하는 세로축, 가로축 좌표 정숫값으로 지정하는 방식
- loc[] : 명칭 기반 인덱싱. 데이터 프레임의 인덱스 값으로 행 위치를, 칼럼의 명칭으로 열 위치를 지정하는 방식

In [360]:
data = {'Name' : ['Chulmin','Eunkyung','Jinwoong','Seebeom'],
        'Year' : [2011,2016,2015,2015],
        'Gender' : ['Male','Female','Male','Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Seebeom  2015    Male

In [364]:
# 첫 번째 행, 첫 번째 열의 데이터 추출: 위치 기반 인덱싱
data_df.iloc[0,0]

'Chulmin'

In [368]:
# 인덱스 값이나 칼럼명을 입력하면 오류를 발생시킴
data_df.iloc[0,'Name']
data_df.iloc['one',0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [374]:
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Seebeom  2015    Male

In [382]:
data_df.iloc[1,0] #두번째 행의 첫번째 열 위치에 있는 단일값 반환

'Eunkyung'

In [380]:
data_df.iloc[2,1] #세번째 행의 두번째 열 위치에 있는 단일값 반환

2015

In [384]:
data_df.iloc[0:2, [0,1]]

Name  Year
one   Chulmin  2011
two  Eunkyung  2016

In [386]:
data_df.iloc[0:2, 0:3]

Name  Year  Gender
one   Chulmin  2011    Male
two  Eunkyung  2016  Female

In [388]:
data_df.iloc[:] #전체 DF 반환

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Seebeom  2015    Male

In [390]:
data_df.iloc[:,:] #전체 DF 반환

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Seebeom  2015    Male

In [392]:
print("\n 맨 마지막 칼럼 데이터 [:, -1] \n", data_df.iloc[:, -1])
print("\n 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] \n", data_df.iloc[:, :-1])


 맨 마지막 칼럼 데이터 [:, -1] 
 one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object

 맨 마지막 칼럼을 제외한 모든 데이터 [:, :-1] 
            Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Seebeom  2015


- iloc[]은 불린 인덱싱은 제공하지 않음

### DataFrame loc[] 연산자

In [395]:
data_df.loc['one','Name']

'Chulmin'

In [397]:
# 다음 코드는 오류를 발생시킴
data_df.loc[0, 'Name']

KeyError: 0

- loc[]에 슬라이싱 기호를 적용하면 종료 값 -1이 아니라 종료 값까지 포함
- -1을 사용할 수 없음

In [402]:
print('위치기반 iloc slicing \n', data_df.iloc[0:1, 0], '\n')
print('명칭기반 loc slicing \n', data_df.loc['one':'two','Name'])

위치기반 iloc slicing 
 one    Chulmin
Name: Name, dtype: object 

명칭기반 loc slicing 
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object


In [404]:
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Seebeom  2015    Male

In [406]:
data_df.loc['three','Name']

'Jinwoong'

In [408]:
data_df.loc['one':'two', ['Name','Year']]

Name  Year
one   Chulmin  2011
two  Eunkyung  2016

In [410]:
data_df.loc['one':'three', 'Name':'Gender']

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male

In [412]:
data_df.loc[:]

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Seebeom  2015    Male

In [416]:
data_df.loc[data_df.Year >= 2014] #불린 인덱싱 가능

Name  Year  Gender
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Seebeom  2015    Male

### <정리> [ ], iloc[ ], loc[ ]의 특징과 주의점

- 개별 또는 여러 칼럼 값 전체를 추출하고자 하면 data_df['Name']과 같이 DataFrame['칼럼명']으로 충분.
  하지만 행과 열을 함께 사용하여 데이터를 추출해야한다면 iloc[]이나 loc[] 사용
- DF의 인덱스나 칼럼명으로 데이터에 접근하는 것은 명칭 기반 인덱싱, 0부터 시작하는 행, 열의 위치 좌표에만 의존하는 것이 위치 기반 인덱싱
- iloc[]은 위치 기반 인덱싱만 가능. 따라서 행과 열 위치 값으로 정수형 값을 지정해 원하는 데이터를 반환
- loc[]은 명칭 기반 인덱싱만 가능. 따라서 행 위치에 DF 인덱스가 오며, 열 위치에는 칼럼명을 지정해 원하는 데이터를 반환
- 명칭 기반 인덱싱에서 슬라이싱을 '시작점:종료점'으로 지정할 때 시작점에서 종료점을 포함한 위치에 있는 데이터를 반환

### 불린 인덱싱

In [420]:
titanic_df = pd.read_csv('titanic_train.csv')
titanic_boolean = titanic_df[ titanic_df['Age'] > 60 ]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [427]:
titanic_df[ titanic_df['Age']>60][['Name','Age']].head(3)
#칼럼이 2개 이상으므로 [[ ]] 사용

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [429]:
titanic_df.loc[titanic_df['Age']>60, ['Name','Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [431]:
# 나이가 60세 이상이고, 선실 등급이 1등급이며, 성별이 여성인 승객 추출
titanic_df[ (titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female') ]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [433]:
# 개별 조건을 변수에 할당하고 이들 변수를 결합해서 불린 인덱싱을 수행할 수도 있음
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[ cond1&cond2&cond3 ]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

## 정렬, Aggregation 함수, GroupBy 적용

### DataFrame, Series의 정렬 - sort_values( )
- sort_values() 주요 입력 파라미터:
    - by: 특정 칼럼으로 정렬 수행
    - ascending=True: 오름차순, False은 내림차순
    - inplace=False: 호출한 DF은 그대로 유지, 정렬된 DF을 반환

In [439]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [443]:
#여러 개의 칼럼으로 정렬하려면 by에 리스트 형식으로 정렬하려는 칼럼 입력
titanic_sorted = titanic_df.sort_values(by=['Pclass','Name'], ascending=False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

### Aggregation 함수 적용

- 모든 칼럼에 count() 결과 반환
- null 값 반영하지 않은 결과 반환

In [446]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [448]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

### groupby() 적용

- by에 칼럼을 입력하면 대상 칼럼으로 groupby 됨
- DataFrameGroupBy라는 또 다른 형태의 DF을 반환
- groupby()를 호출해 반환된 결과에 aggregation 함수를 호출하면 groupby() 대상 칼럼을 제외한 모든 칼럼에 해당 aggregation 함수 적용

In [451]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [454]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [459]:
# PassengerId와 Survived 칼럼에만 count() 수행
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [469]:
# 여러 개의 aggregation 함수를 적용하려면 함수명을 DataFrameGoupBy 객체의 agg() 내의 인자로 입력
titanic_df.groupby('Pclass')['Age'].agg(['max','min'])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [475]:
# 여러 개의 칼럼이 서로 다른 aggregation 함수를 호출하려면 agg() 내에 입력값으로 딕셔너리 형태로 agg이 적용될 칼럼들과 agg 함수를 입력
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

## 결손 데이터 처리하기

### isna()로 결손 데이터 여부 확인


In [478]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked
0        False     False   False  False  False  False  False  False   False  False   True     False
1        False     False   False  False  False  False  False  False   False  False  False     False
2        False     False   False  False  False  False  False  False   False  False   True     False

In [482]:
# 결손 데이터 개수 구하기: sum()
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### fillna()로 결손 데이터 대체하기
- fillna()를 이용해 반환 값을 다시 받거나 inplace=True 파라미터를 fillna()에 추가해야 실제 데이터 세트 값이 변경됨

In [487]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [490]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## apply lambda 식으로 데이터 가공

- lambda는 함수의 선언과 함수 내의 처리를 한 줄의 식으로 쉽게 변환하는 식
- lambda x : x**2
- 왼쪽 x는 입력 인자, 오른쪽 계산식은 반환 값을 의미
- 여러 개의 값을 입력 인자로 사용해야 할 경우에는 map() 함수를 결합해서 사용

In [493]:
def get_square(a):
    return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9


In [502]:
a = [1,2,3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [507]:
# Name 칼럼의 문자열 개수를 Name_len에 생성
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [509]:
# 나이가 15세 미만이면 Child, 아니면 Adult로 구분하는 새로운 칼럼 Child_Adult
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else 'Adult')
titanic_df[['Age','Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

- lambda 식의 if else:
    - ':'의 오른쪽 값은 반환값이므로 반환값이 먼저 나오고 if 식이 나중에 옴
    - else의 경우는 else 식이 먼저 나오고 반환 값이 나중에 옴
- else if는 지원하지 않음

In [512]:
# Child, Adult, Elderly로 분류하는 Age_Cat
titanic_df['Age_Cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 
                                                else ('Adult' if x<=60 
                                                      else 'Elderly'))
titanic_df['Age_Cat'].value_counts()

Age_Cat
Adult      786
Child       83
Elderly     22
Name: count, dtype: int64

- else if이 많이 나와야 하는 경우나 switch case 문의 경우는 별도의 함수를 만드는 게 나음

In [517]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age) :
    cat=''
    if age <= 5 : cat = 'Baby'
    elif age <= 12 : cat = 'Child'
    elif age <= 18 : cat = 'Teenager'
    elif age <= 25 : cat = 'Student'
    elif age <= 35 : cat = 'Young Adult'
    elif age <= 60 : cat = 'Adult'
    else : cat = 'Elderly'
    return cat

# lambda 식에 위에서 생성한 get_category() 함수를 반환값으로 지정
# get_category(x)는 입력값으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()


Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult